// thingProperties.h
// Code generated by Arduino IoT Cloud, customized for fingerprint project

#ifndef THINGPROPERTIES_H
#define THINGPROPERTIES_H

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// Replace with your actual values if needed
const char DEVICE_LOGIN_NAME[]  = "cc349c88-898d-4c8b-ac97-125d53fb1870";
const char SSID[]               = "Rausis 2.4G";        // Your WiFi SSID
const char PASS[]               = "33544383";         // Your WiFi password
const char DEVICE_KEY[]         = "FCuD1cA2O4en1#AmJmev0h!u5";  // Device secret key

// Cloud variable
String accessLog;

// Callback (optional — you can leave it empty if not used)
void onAccessLogChange();
  // Optional: Do something when accessLog is changed


void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(accessLog, READWRITE, ON_CHANGE, onAccessLogChange);
}

// Connect via WiFi
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

#endif // THINGPROPERTIES_H
